// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using estacionamientos.Data;

#nullable disable

namespace estacionamientos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250814125310_Add_Conductor_y_Playero_TPT")]
    partial class Add_Conductor_y_Playero_TPT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("estacionamientos.Models.Usuario", b =>
                {
                    b.Property<int>("UsuNU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UsuNU");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuNU"));

                    b.Property<string>("UsuEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("UsuEmail");

                    b.Property<string>("UsuNumTel")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("UsuNumTel");

                    b.Property<string>("UsuNyA")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("UsuNyA");

                    b.Property<string>("UsuPswd")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("UsuPswd");

                    b.HasKey("UsuNU");

                    b.HasIndex("UsuEmail")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("estacionamientos.Models.Conductor", b =>
                {
                    b.HasBaseType("estacionamientos.Models.Usuario");

                    b.ToTable("Conductor", (string)null);
                });

            modelBuilder.Entity("estacionamientos.Models.Duenio", b =>
                {
                    b.HasBaseType("estacionamientos.Models.Usuario");

                    b.Property<string>("DueCuit")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("DueCuit");

                    b.HasIndex("DueCuit")
                        .IsUnique();

                    b.ToTable("Duenio", (string)null);
                });

            modelBuilder.Entity("estacionamientos.Models.Playero", b =>
                {
                    b.HasBaseType("estacionamientos.Models.Usuario");

                    b.ToTable("Playero", (string)null);
                });

            modelBuilder.Entity("estacionamientos.Models.Conductor", b =>
                {
                    b.HasOne("estacionamientos.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("estacionamientos.Models.Conductor", "UsuNU")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("estacionamientos.Models.Duenio", b =>
                {
                    b.HasOne("estacionamientos.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("estacionamientos.Models.Duenio", "UsuNU")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("estacionamientos.Models.Playero", b =>
                {
                    b.HasOne("estacionamientos.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("estacionamientos.Models.Playero", "UsuNU")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
